using System.ComponentModel;
using System.Globalization;

namespace RoboKeep.Localization;

/// <summary>
/// Provider di localizzazione runtime (IT/EN/ES/FR/DE). Espone le stringhe tramite
/// indicizzatore e notifica <c>Item[]</c> al cambio lingua, così i binding XAML si
/// aggiornano in tempo reale. Le chiavi mancanti ripiegano sull'inglese.
/// </summary>
public sealed class Loc : INotifyPropertyChanged
{
    // Lazy: garantisce che i dizionari static (sotto) siano inizializzati prima del costruttore.
    private static Loc? _instance;
    public static Loc Instance => _instance ??= new Loc();

    /// <summary>Lingue supportate (codice ISO a 2 lettere).</summary>
    public static readonly string[] Supported = { "it", "en", "es", "fr", "de" };

    private Dictionary<string, string> _cur;

    private Loc()
    {
        Language = DetectSystemLanguage();
        _cur = Langs[Language];
    }

    /// <summary>Codice lingua corrente.</summary>
    public string Language { get; private set; }

    /// <summary>Stringa localizzata; se mancante ripiega sull'inglese, poi sulla chiave.</summary>
    public string this[string key] =>
        _cur.TryGetValue(key, out var v) ? v
        : En.TryGetValue(key, out var e) ? e
        : key;

    public string T(string key) => this[key];

    public event PropertyChangedEventHandler? PropertyChanged;

    public void SetLanguage(string lang)
    {
        lang = Normalize(lang);
        if (lang == Language) return;
        Apply(lang);
    }

    /// <summary>Applica l'impostazione: codice lingua valido = forzata, altro = auto da Windows.</summary>
    public void ApplyFromSetting(string? setting)
    {
        var lang = (setting is not null && Supported.Contains(setting)) ? setting : DetectSystemLanguage();
        Apply(lang);
    }

    private void Apply(string lang)
    {
        Language = lang;
        _cur = Langs[lang];
        ApplyCulture(lang);
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Language)));
    }

    private static string Normalize(string lang) => Supported.Contains(lang) ? lang : "en";

    private static string DetectSystemLanguage()
    {
        var code = CultureInfo.InstalledUICulture.TwoLetterISOLanguageName;
        return Supported.Contains(code) ? code : "en";
    }

    private static void ApplyCulture(string lang)
    {
        var ci = new CultureInfo(lang);
        CultureInfo.CurrentUICulture = ci;
        CultureInfo.DefaultThreadCurrentUICulture = ci;
        // I testi Core (report/email) girano su thread di background: impostiamo la lingua
        // esplicitamente, senza dipendere dalla cultura del thread.
        RoboKeep.Core.CoreLoc.SetLanguage(lang);
    }

    // ---------------- ITALIANO ----------------
    private static readonly Dictionary<string, string> It = new()
    {
        ["Common_Browse"] = "Sfoglia…",
        ["Common_Save"] = "Salva",
        ["Common_Cancel"] = "Annulla",
        ["Common_MissingData"] = "Dati mancanti",
        ["Common_Confirm"] = "Conferma",

        ["Main_Title"] = "RoboKeep — Backup configurabile",
        ["Main_New"] = "Nuovo",
        ["Main_Edit"] = "Modifica",
        ["Main_Delete"] = "Elimina",
        ["Main_MoveUpTip"] = "Sposta su (priorità più alta)",
        ["Main_MoveDownTip"] = "Sposta giù (priorità più bassa)",
        ["Main_Preview"] = "Anteprima",
        ["Main_RunSelected"] = "Avvia selezionato",
        ["Main_RunAll"] = "Avvia tutti",
        ["Main_Settings"] = "Impostazioni",
        ["Main_LogTitle"] = "Log esecuzione",
        ["Main_Clear"] = "Pulisci",
        ["Main_Refresh"] = "Aggiorna",
        ["DragHint"] = "Trascina per riordinare",

        ["Col_Active"] = "Attivo",
        ["Col_Name"] = "Nome",
        ["Col_Mode"] = "Modalità",
        ["Col_Source"] = "Sorgente",
        ["Col_Dest"] = "Destinazione",
        ["Col_LastResult"] = "Ultimo esito",

        ["Empty_Title"] = "Nessun job configurato",
        ["Empty_Desc"] = "Crea il primo backup: scegli una cartella sorgente e una destinazione.",
        ["Empty_Button"] = "Crea il primo job",

        ["Status_Running"] = "Esecuzione in corso…",
        ["Status_JobsConfigured"] = "{0} job configurati",

        ["Mode_Mirror"] = "Mirror",
        ["Mode_CopyOnly"] = "Solo copia",

        ["Run_Preview"] = "ANTEPRIMA",
        ["Run_Execution"] = "ESECUZIONE",
        ["Run_PreviewStatus"] = "anteprima…",
        ["Run_InProgress"] = "in corso…",
        ["Run_OK"] = "OK",
        ["Run_Error"] = "ERRORE",
        ["Run_Cancelled"] = "annullato",
        ["Run_CancelledUser"] = "annullato dall'utente",
        ["Stat_Copied"] = "copiati",
        ["Stat_Unchanged"] = "invariati",
        ["Stat_Extra"] = "extra",
        ["Stat_Errors"] = "errori",

        ["Delete_Confirm"] = "Eliminare il job '{0}'?",

        ["Editor_TitleEdit"] = "Modifica job",
        ["Editor_NewJobName"] = "Nuovo job",
        ["Editor_Name"] = "Nome",
        ["Editor_NamePlaceholder"] = "es. Documenti",
        ["Editor_Source"] = "Sorgente",
        ["Editor_Dest"] = "Destinazione",
        ["Editor_Mirror"] = "Mirror — rende la destinazione identica alla sorgente (CANCELLA i file rimossi)",
        ["Editor_MirrorHint"] = "Disattivato = copia e aggiorna soltanto, senza mai cancellare in destinazione.",
        ["Editor_ExcludeOlder"] = "Non sovrascrivere i file più recenti in destinazione (/XO)",
        ["Editor_CopyAll"] = "Copia anche ACL/owner (/COPYALL — utile su share di rete)",
        ["Editor_BigJ"] = "Ottimizza file grandi (/J — I/O non bufferizzato)",
        ["Editor_BigJTip"] = "Per file molto grandi (multi-GB): bypassa la cache del file system, spesso più veloce su SSD/NVMe e reti veloci. Non aiuta i file piccoli. Si esclude a vicenda con la copia riavviabile.",
        ["Editor_RestartZ"] = "Copia riavviabile (/Z — riprende se interrotta)",
        ["Editor_RestartZTip"] = "Riprende la copia di un file grande se si interrompe (utile su VPN, Wi-Fi o reti inaffidabili). Ha un po' di overhead: su reti stabili è meglio lasciarla spenta. Si esclude a vicenda con l'ottimizzazione file grandi.",
        ["Editor_LogAll"] = "Registra tutti i file nel log (anche quelli saltati)",
        ["Editor_LogAllTip"] = "Aggiunge /V: nel log compaiono anche i file identici/saltati, non solo i copiati. Log molto più voluminoso e rallenta l'esecuzione (una riga per ogni file). Tienila spenta se non ti serve il dettaglio.",
        ["Editor_Threads"] = "Thread (/MT)",
        ["Editor_ThreadsTip"] = "Numero di file copiati in parallelo (multi-thread). Più alto = più veloce, soprattutto con tanti file piccoli. 8 va bene quasi sempre; 16+ su SSD o share di rete veloci; su hard disk meccanici meglio non esagerare (può far sbattere la testina). 0 disattiva il multi-thread.",
        ["Editor_Retries"] = "Tentativi (/R)",
        ["Editor_RetriesTip"] = "Quante volte riprovare a copiare un file se la copia fallisce (es. file temporaneamente in uso o rete instabile). Con file spesso aperti tieni un valore basso (1) per non aspettare a lungo.",
        ["Editor_Wait"] = "Attesa sec (/W)",
        ["Editor_WaitTip"] = "Secondi di attesa tra un tentativo e l'altro. Si combina con i Tentativi (es. 1 tentativo × 5 sec). Valori alti allungano molto i tempi se ci sono file problematici.",
        ["Editor_Credential"] = "Credenziale di rete (per share UNC)",
        ["Editor_CredentialTip"] = "Serve solo se sorgente o destinazione è una cartella di rete condivisa (\\\\server\\condivisione) che richiede utente e password. Le credenziali si creano in Impostazioni → Credenziali. Per dischi locali o USB lascia «nessuna».",
        ["Editor_ExcludeFiles"] = "Escludi file (uno per riga)",
        ["Editor_ExcludeFilesTip"] = "Schemi di file da NON copiare, uno per riga. Esempi: *.tmp (tutti i .tmp), ~$* (temporanei di Office), *.log. Lascia vuoto per copiare tutto.",
        ["Editor_ExcludeDirs"] = "Escludi cartelle (una per riga)",
        ["Editor_ExcludeDirsTip"] = "Nomi di cartelle da saltare, una per riga. Esempi: cache, node_modules, Temp. Vengono escluse ovunque compaiano nell'albero.",
        ["Editor_ForceCopy"] = "Forza copia (ignora data/dimensione)",
        ["Editor_ForceCopyTip"] = "File ricopiati anche se data e dimensione non cambiano (es. container, DB, archivi .pst). Uno per riga, per nome o estensione. Vengono ricopiati interi a ogni backup, salvo attivare l'opzione qui sotto.",
        ["Editor_ForceCopySmart"] = "Copia solo se il contenuto è cambiato (calcola hash; più lento in lettura)",
        ["Editor_ForceCopySmartTip"] = "Con questa opzione l'app calcola un hash SHA256 di ogni file in elenco e lo ricopia solo se è davvero cambiato dall'ultimo backup. Utile per file grandi che cambiano di rado; ogni backup deve però leggerli per intero.",
        ["Editor_ForceCopyPreviewSmart"] = "<file modificati>",
        ["Wiz_Title"] = "Nuovo job — creazione guidata",
        ["Wiz_Step"] = "Passo {0} di {1}",
        ["Wiz_Back"] = "Indietro",
        ["Wiz_Next"] = "Avanti",
        ["Wiz_Open"] = "Apri nell'editor",
        ["Wiz_Skip"] = "Salta e configura a mano",
        ["Wiz_Step1Title"] = "Dati di base",
        ["Wiz_Step2Title"] = "Tipo di dischi",
        ["Wiz_Step3Title"] = "Comportamento",
        ["Wiz_Step4Title"] = "Casi speciali",
        ["Wiz_Step5Title"] = "Riepilogo",
        ["Wiz_SourceKind"] = "Tipo della sorgente",
        ["Wiz_DestKind"] = "Tipo della destinazione",
        ["Wiz_KindHint"] = "Con un disco fisso (HDD) pochi thread vanno più veloci; SSD e rete reggono più parallelismo.",
        ["Wiz_Ssd"] = "SSD / NVMe",
        ["Wiz_Hdd"] = "Disco fisso (HDD)",
        ["Wiz_Usb"] = "USB esterno",
        ["Wiz_Network"] = "Share di rete",
        ["Wiz_SyncQuestion"] = "La destinazione deve…",
        ["Wiz_SyncMirror"] = "Rispecchiare la sorgente (elimina anche i file rimossi)",
        ["Wiz_SyncAccumulate"] = "Accumulare (non cancella mai nulla)",
        ["Wiz_Large"] = "Ci sono file molto grandi (VM, container, archivi multi-GB)",
        ["Wiz_Frozen"] = "Ho file il cui contenuto cambia ma data e dimensione restano uguali",
        ["Wiz_FrozenHint"] = "Es. container VeraCrypt o database. Se è VeraCrypt, conviene disattivare il flag che conserva la data del container invece di ricopiarlo ogni volta.",
        ["Wiz_FrozenPatterns"] = "Pattern (uno per riga, es. *.vc)",
        ["Wiz_Perms"] = "Conserva permessi/ACL e proprietari dei file",
        ["Wiz_PermsHint"] = "Serve per ripristinare su un altro PC/server; può causare accesso negato nelle ricopie.",
        ["Wiz_Excl"] = "Escludi cartelle cache e file temporanei comuni",
        ["Wiz_Summary"] = "Cosa verrà impostato",
        ["Wiz_NetCredNote"] = "Sorgente o destinazione in rete: ricordati di impostare la credenziale nell'editor.",
        ["Editor_CommandPreview"] = "Anteprima comando robocopy",
        ["Editor_Val_Name"] = "Il nome del job è obbligatorio.",
        ["Editor_Val_Source"] = "La cartella sorgente è obbligatoria.",
        ["Editor_Val_Dest"] = "La cartella destinazione è obbligatoria.",
        ["Editor_BrowseTitle"] = "Seleziona cartella",
        ["Cred_NoneLocal"] = "(nessuna — percorso locale)",

        ["Settings_Title"] = "Impostazioni",
        ["Tab_General"] = "Generale",
        ["Tab_Email"] = "Email",
        ["Tab_Credentials"] = "Credenziali di rete",
        ["Tab_Schedule"] = "Pianificazione",
        ["Tab_About"] = "Info",
        ["About_Version"] = "Versione",
        ["About_Desc"] = "GUI per backup e mirroring basata sul robocopy di Windows.",
        ["About_License"] = "Licenza MIT",
        ["About_BuiltOn"] = "Basato sul robocopy di sistema e .NET 10 (WPF) · 5 lingue",

        ["Set_Language"] = "Lingua",
        ["Lang_Auto"] = "Automatica (Windows)",
        ["Set_LogFolder"] = "Cartella log (archivio per data)",
        ["Set_TempFolder"] = "Cartella temporanea",
        ["Set_PathsHint"] = "I log sono SEMPRE attivi. Se lasci vuoti questi campi, log e file temporanei vanno nelle sottocartelle predefinite mostrate in grigio (accanto all'app). Compila un percorso solo per spostarli altrove.",
        ["Set_Compress"] = "Comprimi i log in .zip",
        ["Set_Retention"] = "Giorni di conservazione log (0 = non eliminare)",
        ["Set_CredSecurity"] = "Sicurezza credenziali",
        ["Set_CredScopeUser"] = "Cifra le password solo per il mio utente Windows (più sicuro)",
        ["Set_CredScopeHint"] = "Attivo: password (credenziali ed email) decifrabili solo dal tuo utente; in compenso l'esecuzione pianificata deve girare con il tuo stesso utente. Disattivo: legate al PC, funzionano con qualsiasi utente (comodo per la schedulazione). Cambiando l'opzione, le password già salvate vengono ri-cifrate in automatico.",

        ["Email_Enable"] = "Abilita notifiche email",
        ["Email_OnlyError"] = "Invia solo in caso di errore",
        ["Email_Smtp"] = "Server SMTP",
        ["Email_Port"] = "Porta",
        ["Email_Ssl"] = "Usa SSL/TLS",
        ["Email_From"] = "Da (mittente)",
        ["Email_To"] = "A (destinatario)",
        ["Email_User"] = "Utente SMTP (facoltativo)",
        ["Email_Pwd"] = "Password SMTP (lascia vuoto per non modificare)",
        ["Email_TestButton"] = "Invia email di prova",
        ["Email_TestSending"] = "Invio in corso…",
        ["Email_TestSent"] = "Email di prova inviata. Controlla la casella (o l'inbox di Mailtrap).",
        ["Common_Error"] = "Errore: {0}",

        ["Cred_AddUpdate"] = "Aggiungi / aggiorna credenziale",
        ["Cred_Name"] = "Nome",
        ["Cred_Host"] = "Host/Share (\\\\server\\share)",
        ["Cred_User"] = "Utente (DOMINIO\\utente)",
        ["Cred_Pwd"] = "Password",
        ["Cred_Save"] = "Salva credenziali",
        ["Cred_Remove"] = "Rimuovi selezionata",
        ["Cred_ColUser"] = "Utente",
        ["Cred_NameRequired"] = "Il nome della credenziale è obbligatorio.",
        ["Conn_Test"] = "Testa connessione",
        ["Conn_Testing"] = "Verifica…",
        ["Conn_Ok"] = "Connessione riuscita.",
        ["Conn_LogonFail"] = "Nome utente o password non corretti.",
        ["Conn_PathNotFound"] = "Percorso di rete non trovato (host irraggiungibile).",
        ["Conn_NameNotFound"] = "Condivisione inesistente.",
        ["Conn_AccessDenied"] = "Accesso negato.",
        ["Conn_Generic"] = "Errore di connessione (codice {0}).",

        ["Sched_InfoTitle"] = "Esecuzione automatica",
        ["Sched_InfoMsg"] = "Registra un'attività in Utilità di pianificazione di Windows che esegue «Avvia tutti» in modalità silenziosa all'orario scelto.",
        ["Sched_Time"] = "Orario (HH:mm)",
        ["Sched_Freq"] = "Frequenza",
        ["Sched_Daily"] = "Giornaliera",
        ["Sched_Weekly"] = "Settimanale",
        ["Sched_Once"] = "Una volta sola",
        ["Sched_Next"] = "Prossima esecuzione: {0}",
        ["Sched_None"] = "Nessuna pianificazione attiva.",
        ["Sched_Create"] = "Crea / aggiorna attività",
        ["Sched_Remove"] = "Rimuovi attività",
        ["Sched_BadTime"] = "Orario non valido. Usa il formato HH:mm.",
        ["Sched_Created"] = "Attività pianificata creata/aggiornata per le {0}.",
        ["Sched_Removed"] = "Attività pianificata rimossa.",
        ["Sched_Error"] = "Errore: {0}",

        ["Health_BannerTitle"] = "Attenzione ai backup",
        ["Health_BannerFormat"] = "Job con problemi: {0} falliti, {1} fermi da troppo tempo.",

        ["Preflight_ConfirmTitle"] = "Controlli pre-avvio",
        ["Preflight_ConfirmIntro"] = "Alcuni controlli segnalano possibili problemi. Avviare comunque?",
        ["Preflight_DestUnreachable"] = "destinazione non raggiungibile",
        ["Preflight_LowSpace"] = "spazio libero basso:",
        ["Preflight_SourceBigger"] = "la sorgente potrebbe non entrare; richiede:",

        ["Tray_Open"] = "Apri",
        ["Tray_RunAll"] = "Avvia tutti",
        ["Tray_Exit"] = "Esci",
        ["Toast_Ok"] = "Backup completato",
        ["Toast_Error"] = "Backup con errori",
    };

    // ---------------- ENGLISH ----------------
    private static readonly Dictionary<string, string> En = new()
    {
        ["Common_Browse"] = "Browse…",
        ["Common_Save"] = "Save",
        ["Common_Cancel"] = "Cancel",
        ["Common_MissingData"] = "Missing data",
        ["Common_Confirm"] = "Confirm",

        ["Main_Title"] = "RoboKeep — Configurable backup",
        ["Main_New"] = "New",
        ["Main_Edit"] = "Edit",
        ["Main_Delete"] = "Delete",
        ["Main_MoveUpTip"] = "Move up (higher priority)",
        ["Main_MoveDownTip"] = "Move down (lower priority)",
        ["Main_Preview"] = "Preview",
        ["Main_RunSelected"] = "Run selected",
        ["Main_RunAll"] = "Run all",
        ["Main_Settings"] = "Settings",
        ["Main_LogTitle"] = "Execution log",
        ["Main_Clear"] = "Clear",
        ["Main_Refresh"] = "Refresh",
        ["DragHint"] = "Drag to reorder",

        ["Col_Active"] = "Enabled",
        ["Col_Name"] = "Name",
        ["Col_Mode"] = "Mode",
        ["Col_Source"] = "Source",
        ["Col_Dest"] = "Destination",
        ["Col_LastResult"] = "Last result",

        ["Empty_Title"] = "No jobs configured",
        ["Empty_Desc"] = "Create your first backup: pick a source folder and a destination.",
        ["Empty_Button"] = "Create the first job",

        ["Status_Running"] = "Running…",
        ["Status_JobsConfigured"] = "{0} configured jobs",

        ["Mode_Mirror"] = "Mirror",
        ["Mode_CopyOnly"] = "Copy only",

        ["Run_Preview"] = "PREVIEW",
        ["Run_Execution"] = "RUN",
        ["Run_PreviewStatus"] = "preview…",
        ["Run_InProgress"] = "running…",
        ["Run_OK"] = "OK",
        ["Run_Error"] = "ERROR",
        ["Run_Cancelled"] = "cancelled",
        ["Run_CancelledUser"] = "cancelled by user",
        ["Stat_Copied"] = "copied",
        ["Stat_Unchanged"] = "unchanged",
        ["Stat_Extra"] = "extra",
        ["Stat_Errors"] = "errors",

        ["Delete_Confirm"] = "Delete job '{0}'?",

        ["Editor_TitleEdit"] = "Edit job",
        ["Editor_NewJobName"] = "New job",
        ["Editor_Name"] = "Name",
        ["Editor_NamePlaceholder"] = "e.g. Documents",
        ["Editor_Source"] = "Source",
        ["Editor_Dest"] = "Destination",
        ["Editor_Mirror"] = "Mirror — makes the destination identical to the source (DELETES removed files)",
        ["Editor_MirrorHint"] = "Off = only copies and updates, never deletes at the destination.",
        ["Editor_ExcludeOlder"] = "Do not overwrite newer files at the destination (/XO)",
        ["Editor_CopyAll"] = "Also copy ACLs/owner (/COPYALL — useful on network shares)",
        ["Editor_BigJ"] = "Optimize large files (/J — unbuffered I/O)",
        ["Editor_BigJTip"] = "For very large files (multi-GB): bypasses the file system cache, often faster on SSD/NVMe and fast networks. Does not help small files. Mutually exclusive with restartable copy.",
        ["Editor_RestartZ"] = "Restartable copy (/Z — resumes if interrupted)",
        ["Editor_RestartZTip"] = "Resumes copying a large file if it gets interrupted (useful over VPN, Wi-Fi or unreliable networks). It has some overhead: on stable networks it is better left off. Mutually exclusive with large-file optimization.",
        ["Editor_LogAll"] = "Log all files (including skipped ones)",
        ["Editor_LogAllTip"] = "Adds /V: the log also lists identical/skipped files, not just copied ones. Much larger log and it slows down the run (one line per file). Leave off unless you need the detail.",
        ["Editor_Threads"] = "Threads (/MT)",
        ["Editor_ThreadsTip"] = "Number of files copied in parallel (multi-thread). Higher = faster, especially with many small files. 8 is fine almost always; 16+ on SSDs or fast network shares; on mechanical hard disks don't overdo it (it can thrash the head). 0 disables multi-thread.",
        ["Editor_Retries"] = "Retries (/R)",
        ["Editor_RetriesTip"] = "How many times to retry copying a file if the copy fails (e.g. a file temporarily in use or an unstable network). With often-open files keep a low value (1) to avoid long waits.",
        ["Editor_Wait"] = "Wait sec (/W)",
        ["Editor_WaitTip"] = "Seconds to wait between retries. Combines with Retries (e.g. 1 retry × 5 sec). High values greatly increase times if there are problematic files.",
        ["Editor_Credential"] = "Network credential (for UNC shares)",
        ["Editor_CredentialTip"] = "Only needed if the source or destination is a shared network folder (\\\\server\\share) requiring a username and password. Credentials are created in Settings → Credentials. For local or USB disks leave «none».",
        ["Editor_ExcludeFiles"] = "Exclude files (one per line)",
        ["Editor_ExcludeFilesTip"] = "File patterns NOT to copy, one per line. Examples: *.tmp (all .tmp), ~$* (Office temp files), *.log. Leave empty to copy everything.",
        ["Editor_ExcludeDirs"] = "Exclude folders (one per line)",
        ["Editor_ExcludeDirsTip"] = "Folder names to skip, one per line. Examples: cache, node_modules, Temp. They are excluded wherever they appear in the tree.",
        ["Editor_ForceCopy"] = "Force copy (ignore date/size)",
        ["Editor_ForceCopyTip"] = "Files re-copied even if date and size don't change (e.g. containers, DBs, .pst archives). One per line, by name or extension. They are copied in full on every backup unless you enable the option below.",
        ["Editor_ForceCopySmart"] = "Copy only if content changed (computes hash; slower to read)",
        ["Editor_ForceCopySmartTip"] = "With this option the app computes a SHA256 hash of each listed file and re-copies it only if it actually changed since the last backup. Useful for large files that change rarely; every backup must read them in full.",
        ["Editor_ForceCopyPreviewSmart"] = "<changed files>",
        ["Wiz_Title"] = "New job — guided setup",
        ["Wiz_Step"] = "Step {0} of {1}",
        ["Wiz_Back"] = "Back",
        ["Wiz_Next"] = "Next",
        ["Wiz_Open"] = "Open in editor",
        ["Wiz_Skip"] = "Skip and configure manually",
        ["Wiz_Step1Title"] = "Basics",
        ["Wiz_Step2Title"] = "Disk types",
        ["Wiz_Step3Title"] = "Behavior",
        ["Wiz_Step4Title"] = "Special cases",
        ["Wiz_Step5Title"] = "Summary",
        ["Wiz_SourceKind"] = "Source type",
        ["Wiz_DestKind"] = "Destination type",
        ["Wiz_KindHint"] = "With a spinning disk (HDD) fewer threads are faster; SSD and network handle more parallelism.",
        ["Wiz_Ssd"] = "SSD / NVMe",
        ["Wiz_Hdd"] = "Hard disk (HDD)",
        ["Wiz_Usb"] = "External USB",
        ["Wiz_Network"] = "Network share",
        ["Wiz_SyncQuestion"] = "The destination should…",
        ["Wiz_SyncMirror"] = "Mirror the source (also deletes removed files)",
        ["Wiz_SyncAccumulate"] = "Accumulate (never deletes anything)",
        ["Wiz_Large"] = "There are very large files (VMs, containers, multi-GB archives)",
        ["Wiz_Frozen"] = "I have files whose content changes but date and size stay the same",
        ["Wiz_FrozenHint"] = "E.g. VeraCrypt containers or databases. For VeraCrypt, prefer disabling the container timestamp-preserve option instead of re-copying it every time.",
        ["Wiz_FrozenPatterns"] = "Patterns (one per line, e.g. *.vc)",
        ["Wiz_Perms"] = "Preserve file permissions/ACLs and owners",
        ["Wiz_PermsHint"] = "Needed when restoring to another PC/server; can cause access-denied on re-copies.",
        ["Wiz_Excl"] = "Exclude common cache folders and temporary files",
        ["Wiz_Summary"] = "What will be set",
        ["Wiz_NetCredNote"] = "Source or destination on the network: remember to set the credential in the editor.",
        ["Editor_CommandPreview"] = "Robocopy command preview",
        ["Editor_Val_Name"] = "The job name is required.",
        ["Editor_Val_Source"] = "The source folder is required.",
        ["Editor_Val_Dest"] = "The destination folder is required.",
        ["Editor_BrowseTitle"] = "Select folder",
        ["Cred_NoneLocal"] = "(none — local path)",

        ["Settings_Title"] = "Settings",
        ["Tab_General"] = "General",
        ["Tab_Email"] = "Email",
        ["Tab_Credentials"] = "Network credentials",
        ["Tab_Schedule"] = "Scheduling",
        ["Tab_About"] = "About",
        ["About_Version"] = "Version",
        ["About_Desc"] = "GUI for backups and mirroring built on Windows robocopy.",
        ["About_License"] = "MIT License",
        ["About_BuiltOn"] = "Built on the system robocopy and .NET 10 (WPF) · 5 languages",

        ["Set_Language"] = "Language",
        ["Lang_Auto"] = "Automatic (Windows)",
        ["Set_LogFolder"] = "Log folder (archived by date)",
        ["Set_TempFolder"] = "Temporary folder",
        ["Set_PathsHint"] = "Logs are ALWAYS on. If you leave these fields empty, logs and temporary files go to the default subfolders shown in grey (next to the app). Fill in a path only to move them elsewhere.",
        ["Set_Compress"] = "Compress logs to .zip",
        ["Set_Retention"] = "Log retention days (0 = never delete)",
        ["Set_CredSecurity"] = "Credential security",
        ["Set_CredScopeUser"] = "Encrypt passwords only for my Windows user (more secure)",
        ["Set_CredScopeHint"] = "On: passwords (credentials and email) decryptable only by your user; in exchange the scheduled task must run as your same user. Off: bound to the PC, work with any user (handy for scheduling). When you change the option, already-saved passwords are re-encrypted automatically.",

        ["Email_Enable"] = "Enable email notifications",
        ["Email_OnlyError"] = "Send only on error",
        ["Email_Smtp"] = "SMTP server",
        ["Email_Port"] = "Port",
        ["Email_Ssl"] = "Use SSL/TLS",
        ["Email_From"] = "From (sender)",
        ["Email_To"] = "To (recipient)",
        ["Email_User"] = "SMTP user (optional)",
        ["Email_Pwd"] = "SMTP password (leave blank to keep)",
        ["Email_TestButton"] = "Send test email",
        ["Email_TestSending"] = "Sending…",
        ["Email_TestSent"] = "Test email sent. Check your inbox (or the Mailtrap inbox).",
        ["Common_Error"] = "Error: {0}",

        ["Cred_AddUpdate"] = "Add / update credential",
        ["Cred_Name"] = "Name",
        ["Cred_Host"] = "Host/Share (\\\\server\\share)",
        ["Cred_User"] = "User (DOMAIN\\user)",
        ["Cred_Pwd"] = "Password",
        ["Cred_Save"] = "Save credentials",
        ["Cred_Remove"] = "Remove selected",
        ["Cred_ColUser"] = "User",
        ["Cred_NameRequired"] = "The credential name is required.",
        ["Conn_Test"] = "Test connection",
        ["Conn_Testing"] = "Testing…",
        ["Conn_Ok"] = "Connection successful.",
        ["Conn_LogonFail"] = "Incorrect username or password.",
        ["Conn_PathNotFound"] = "Network path not found (host unreachable).",
        ["Conn_NameNotFound"] = "Share not found.",
        ["Conn_AccessDenied"] = "Access denied.",
        ["Conn_Generic"] = "Connection error (code {0}).",

        ["Sched_InfoTitle"] = "Automatic execution",
        ["Sched_InfoMsg"] = "Registers a task in Windows Task Scheduler that runs «Run all» silently at the chosen time.",
        ["Sched_Time"] = "Time (HH:mm)",
        ["Sched_Freq"] = "Frequency",
        ["Sched_Daily"] = "Daily",
        ["Sched_Weekly"] = "Weekly",
        ["Sched_Once"] = "Once",
        ["Sched_Next"] = "Next run: {0}",
        ["Sched_None"] = "No active schedule.",
        ["Sched_Create"] = "Create / update task",
        ["Sched_Remove"] = "Remove task",
        ["Sched_BadTime"] = "Invalid time. Use the HH:mm format.",
        ["Sched_Created"] = "Scheduled task created/updated for {0}.",
        ["Sched_Removed"] = "Scheduled task removed.",
        ["Sched_Error"] = "Error: {0}",

        ["Health_BannerTitle"] = "Backup warnings",
        ["Health_BannerFormat"] = "Jobs with issues: {0} failed, {1} stale for too long.",

        ["Preflight_ConfirmTitle"] = "Pre-run checks",
        ["Preflight_ConfirmIntro"] = "Some checks report possible problems. Run anyway?",
        ["Preflight_DestUnreachable"] = "destination not reachable",
        ["Preflight_LowSpace"] = "low free space:",
        ["Preflight_SourceBigger"] = "the source may not fit; needs:",

        ["Tray_Open"] = "Open",
        ["Tray_RunAll"] = "Run all",
        ["Tray_Exit"] = "Exit",
        ["Toast_Ok"] = "Backup completed",
        ["Toast_Error"] = "Backup completed with errors",
    };

    // ---------------- ESPAÑOL ----------------
    private static readonly Dictionary<string, string> Es = new()
    {
        ["Common_Browse"] = "Examinar…",
        ["Common_Save"] = "Guardar",
        ["Common_Cancel"] = "Cancelar",
        ["Common_MissingData"] = "Faltan datos",
        ["Common_Confirm"] = "Confirmar",

        ["Main_Title"] = "RoboKeep — Copia de seguridad configurable",
        ["Main_New"] = "Nuevo",
        ["Main_Edit"] = "Editar",
        ["Main_Delete"] = "Eliminar",
        ["Main_MoveUpTip"] = "Subir (mayor prioridad)",
        ["Main_MoveDownTip"] = "Bajar (menor prioridad)",
        ["Main_Preview"] = "Vista previa",
        ["Main_RunSelected"] = "Ejecutar seleccionado",
        ["Main_RunAll"] = "Ejecutar todos",
        ["Main_Settings"] = "Configuración",
        ["Main_LogTitle"] = "Registro de ejecución",
        ["Main_Clear"] = "Limpiar",
        ["Main_Refresh"] = "Actualizar",
        ["DragHint"] = "Arrastra para reordenar",

        ["Col_Active"] = "Activo",
        ["Col_Name"] = "Nombre",
        ["Col_Mode"] = "Modo",
        ["Col_Source"] = "Origen",
        ["Col_Dest"] = "Destino",
        ["Col_LastResult"] = "Último resultado",

        ["Empty_Title"] = "Ningún trabajo configurado",
        ["Empty_Desc"] = "Crea tu primera copia: elige una carpeta de origen y un destino.",
        ["Empty_Button"] = "Crear el primer trabajo",

        ["Status_Running"] = "Ejecutando…",
        ["Status_JobsConfigured"] = "{0} trabajos configurados",

        ["Mode_Mirror"] = "Espejo",
        ["Mode_CopyOnly"] = "Solo copiar",

        ["Run_Preview"] = "VISTA PREVIA",
        ["Run_Execution"] = "EJECUCIÓN",
        ["Run_PreviewStatus"] = "vista previa…",
        ["Run_InProgress"] = "en curso…",
        ["Run_OK"] = "OK",
        ["Run_Error"] = "ERROR",
        ["Run_Cancelled"] = "cancelado",
        ["Run_CancelledUser"] = "cancelado por el usuario",
        ["Stat_Copied"] = "copiados",
        ["Stat_Unchanged"] = "sin cambios",
        ["Stat_Extra"] = "extra",
        ["Stat_Errors"] = "errores",

        ["Delete_Confirm"] = "¿Eliminar el trabajo '{0}'?",

        ["Editor_TitleEdit"] = "Editar trabajo",
        ["Editor_NewJobName"] = "Nuevo trabajo",
        ["Editor_Name"] = "Nombre",
        ["Editor_NamePlaceholder"] = "p. ej. Documentos",
        ["Editor_Source"] = "Origen",
        ["Editor_Dest"] = "Destino",
        ["Editor_Mirror"] = "Espejo — hace el destino idéntico al origen (ELIMINA los archivos quitados)",
        ["Editor_MirrorHint"] = "Desactivado = solo copia y actualiza, nunca elimina en el destino.",
        ["Editor_ExcludeOlder"] = "No sobrescribir los archivos más nuevos del destino (/XO)",
        ["Editor_CopyAll"] = "Copiar también ACL/propietario (/COPYALL — útil en recursos de red)",
        ["Editor_BigJ"] = "Optimizar archivos grandes (/J — E/S sin búfer)",
        ["Editor_BigJTip"] = "Para archivos muy grandes (varios GB): omite la caché del sistema de archivos, a menudo más rápido en SSD/NVMe y redes rápidas. No ayuda con archivos pequeños. Se excluye mutuamente con la copia reanudable.",
        ["Editor_RestartZ"] = "Copia reanudable (/Z — continúa si se interrumpe)",
        ["Editor_RestartZTip"] = "Reanuda la copia de un archivo grande si se interrumpe (útil en VPN, Wi-Fi o redes poco fiables). Tiene cierta sobrecarga: en redes estables es mejor dejarla desactivada. Se excluye mutuamente con la optimización de archivos grandes.",
        ["Editor_LogAll"] = "Registrar todos los archivos (incluidos los omitidos)",
        ["Editor_LogAllTip"] = "Añade /V: el registro también muestra los archivos idénticos/omitidos, no solo los copiados. Registro mucho más voluminoso y ralentiza la ejecución (una línea por archivo). Déjala desactivada si no necesitas el detalle.",
        ["Editor_Threads"] = "Subprocesos (/MT)",
        ["Editor_ThreadsTip"] = "Número de archivos copiados en paralelo (multiproceso). Más alto = más rápido, sobre todo con muchos archivos pequeños. 8 va bien casi siempre; 16+ en SSD o recursos de red rápidos; en discos duros mecánicos no exageres (puede mover mucho el cabezal). 0 desactiva el multiproceso.",
        ["Editor_Retries"] = "Reintentos (/R)",
        ["Editor_RetriesTip"] = "Cuántas veces reintentar copiar un archivo si la copia falla (p. ej. archivo en uso o red inestable). Con archivos a menudo abiertos usa un valor bajo (1) para no esperar mucho.",
        ["Editor_Wait"] = "Espera seg (/W)",
        ["Editor_WaitTip"] = "Segundos de espera entre reintentos. Se combina con los Reintentos (p. ej. 1 reintento × 5 s). Valores altos alargan mucho los tiempos si hay archivos problemáticos.",
        ["Editor_Credential"] = "Credencial de red (para recursos UNC)",
        ["Editor_CredentialTip"] = "Solo se necesita si el origen o el destino es una carpeta de red compartida (\\\\servidor\\recurso) que requiere usuario y contraseña. Las credenciales se crean en Configuración → Credenciales. Para discos locales o USB deja «ninguna».",
        ["Editor_ExcludeFiles"] = "Excluir archivos (uno por línea)",
        ["Editor_ExcludeFilesTip"] = "Patrones de archivos que NO copiar, uno por línea. Ejemplos: *.tmp (todos los .tmp), ~$* (temporales de Office), *.log. Déjalo vacío para copiar todo.",
        ["Editor_ExcludeDirs"] = "Excluir carpetas (una por línea)",
        ["Editor_ExcludeDirsTip"] = "Nombres de carpetas que omitir, una por línea. Ejemplos: cache, node_modules, Temp. Se excluyen dondequiera que aparezcan en el árbol.",
        ["Editor_ForceCopy"] = "Forzar copia (ignorar fecha/tamaño)",
        ["Editor_ForceCopyTip"] = "Archivos que se vuelven a copiar aunque la fecha y el tamaño no cambien (p. ej. contenedores, BD, archivos .pst). Uno por línea, por nombre o extensión. Se copian enteros en cada copia de seguridad salvo que actives la opción de abajo.",
        ["Editor_ForceCopySmart"] = "Copiar solo si el contenido ha cambiado (calcula hash; lectura más lenta)",
        ["Editor_ForceCopySmartTip"] = "Con esta opción la app calcula un hash SHA256 de cada archivo de la lista y solo lo vuelve a copiar si ha cambiado realmente desde la última copia. Útil para archivos grandes que cambian poco; cada copia debe leerlos enteros.",
        ["Editor_ForceCopyPreviewSmart"] = "<archivos modificados>",
        ["Wiz_Title"] = "Nuevo trabajo — asistente de configuración",
        ["Wiz_Step"] = "Paso {0} de {1}",
        ["Wiz_Back"] = "Atrás",
        ["Wiz_Next"] = "Siguiente",
        ["Wiz_Open"] = "Abrir en el editor",
        ["Wiz_Skip"] = "Omitir y configurar manualmente",
        ["Wiz_Step1Title"] = "Datos básicos",
        ["Wiz_Step2Title"] = "Tipo de discos",
        ["Wiz_Step3Title"] = "Comportamiento",
        ["Wiz_Step4Title"] = "Casos especiales",
        ["Wiz_Step5Title"] = "Resumen",
        ["Wiz_SourceKind"] = "Tipo de origen",
        ["Wiz_DestKind"] = "Tipo de destino",
        ["Wiz_KindHint"] = "Con un disco duro (HDD) menos hilos van más rápido; SSD y red admiten más paralelismo.",
        ["Wiz_Ssd"] = "SSD / NVMe",
        ["Wiz_Hdd"] = "Disco duro (HDD)",
        ["Wiz_Usb"] = "USB externo",
        ["Wiz_Network"] = "Recurso compartido de red",
        ["Wiz_SyncQuestion"] = "El destino debe…",
        ["Wiz_SyncMirror"] = "Reflejar el origen (también elimina los archivos borrados)",
        ["Wiz_SyncAccumulate"] = "Acumular (nunca elimina nada)",
        ["Wiz_Large"] = "Hay archivos muy grandes (VM, contenedores, archivos multi-GB)",
        ["Wiz_Frozen"] = "Tengo archivos cuyo contenido cambia pero la fecha y el tamaño permanecen iguales",
        ["Wiz_FrozenHint"] = "P. ej. contenedores VeraCrypt o bases de datos. Para VeraCrypt, conviene desactivar la opción que conserva la fecha del contenedor en lugar de volver a copiarlo cada vez.",
        ["Wiz_FrozenPatterns"] = "Patrones (uno por línea, p. ej. *.vc)",
        ["Wiz_Perms"] = "Conservar permisos/ACL y propietarios de archivos",
        ["Wiz_PermsHint"] = "Necesario para restaurar en otro PC/servidor; puede causar acceso denegado en las recopias.",
        ["Wiz_Excl"] = "Excluir carpetas de caché y archivos temporales comunes",
        ["Wiz_Summary"] = "Qué se va a configurar",
        ["Wiz_NetCredNote"] = "Origen o destino en la red: recuerda establecer la credencial en el editor.",
        ["Editor_CommandPreview"] = "Vista previa del comando robocopy",
        ["Editor_Val_Name"] = "El nombre del trabajo es obligatorio.",
        ["Editor_Val_Source"] = "La carpeta de origen es obligatoria.",
        ["Editor_Val_Dest"] = "La carpeta de destino es obligatoria.",
        ["Editor_BrowseTitle"] = "Seleccionar carpeta",
        ["Cred_NoneLocal"] = "(ninguna — ruta local)",

        ["Settings_Title"] = "Configuración",
        ["Tab_General"] = "General",
        ["Tab_Email"] = "Correo",
        ["Tab_Credentials"] = "Credenciales de red",
        ["Tab_Schedule"] = "Programación",
        ["Tab_About"] = "Acerca de",
        ["About_Version"] = "Versión",
        ["About_Desc"] = "GUI para copias de seguridad y duplicación basada en robocopy de Windows.",
        ["About_License"] = "Licencia MIT",
        ["About_BuiltOn"] = "Basado en el robocopy del sistema y .NET 10 (WPF) · 5 idiomas",

        ["Set_Language"] = "Idioma",
        ["Lang_Auto"] = "Automático (Windows)",
        ["Set_LogFolder"] = "Carpeta de registros (archivado por fecha)",
        ["Set_TempFolder"] = "Carpeta temporal",
        ["Set_PathsHint"] = "Los registros están SIEMPRE activos. Si dejas estos campos vacíos, los registros y los archivos temporales van a las subcarpetas predeterminadas mostradas en gris (junto a la app). Rellena una ruta solo para moverlos a otro sitio.",
        ["Set_Compress"] = "Comprimir los registros en .zip",
        ["Set_Retention"] = "Días de conservación de registros (0 = no eliminar)",
        ["Set_CredSecurity"] = "Seguridad de credenciales",
        ["Set_CredScopeUser"] = "Cifrar las contraseñas solo para mi usuario de Windows (más seguro)",
        ["Set_CredScopeHint"] = "Activo: contraseñas (credenciales y correo) descifrables solo por tu usuario; a cambio la tarea programada debe ejecutarse con tu mismo usuario. Inactivo: ligadas al PC, funcionan con cualquier usuario (cómodo para la programación). Al cambiar la opción, las contraseñas ya guardadas se vuelven a cifrar automáticamente.",

        ["Email_Enable"] = "Activar notificaciones por correo",
        ["Email_OnlyError"] = "Enviar solo en caso de error",
        ["Email_Smtp"] = "Servidor SMTP",
        ["Email_Port"] = "Puerto",
        ["Email_Ssl"] = "Usar SSL/TLS",
        ["Email_From"] = "De (remitente)",
        ["Email_To"] = "Para (destinatario)",
        ["Email_User"] = "Usuario SMTP (opcional)",
        ["Email_Pwd"] = "Contraseña SMTP (deja en blanco para no cambiar)",
        ["Email_TestButton"] = "Enviar correo de prueba",
        ["Email_TestSending"] = "Enviando…",
        ["Email_TestSent"] = "Correo de prueba enviado. Revisa tu bandeja (o la inbox de Mailtrap).",
        ["Common_Error"] = "Error: {0}",

        ["Cred_AddUpdate"] = "Añadir / actualizar credencial",
        ["Cred_Name"] = "Nombre",
        ["Cred_Host"] = "Host/Recurso (\\\\servidor\\recurso)",
        ["Cred_User"] = "Usuario (DOMINIO\\usuario)",
        ["Cred_Pwd"] = "Contraseña",
        ["Cred_Save"] = "Guardar credenciales",
        ["Cred_Remove"] = "Quitar seleccionada",
        ["Cred_ColUser"] = "Usuario",
        ["Cred_NameRequired"] = "El nombre de la credencial es obligatorio.",
        ["Conn_Test"] = "Probar conexión",
        ["Conn_Testing"] = "Probando…",
        ["Conn_Ok"] = "Conexión correcta.",
        ["Conn_LogonFail"] = "Usuario o contraseña incorrectos.",
        ["Conn_PathNotFound"] = "Ruta de red no encontrada (host inaccesible).",
        ["Conn_NameNotFound"] = "Recurso compartido inexistente.",
        ["Conn_AccessDenied"] = "Acceso denegado.",
        ["Conn_Generic"] = "Error de conexión (código {0}).",

        ["Sched_InfoTitle"] = "Ejecución automática",
        ["Sched_InfoMsg"] = "Registra una tarea en el Programador de tareas de Windows que ejecuta «Ejecutar todos» en silencio a la hora elegida.",
        ["Sched_Time"] = "Hora (HH:mm)",
        ["Sched_Freq"] = "Frecuencia",
        ["Sched_Daily"] = "Diaria",
        ["Sched_Weekly"] = "Semanal",
        ["Sched_Once"] = "Una sola vez",
        ["Sched_Next"] = "Próxima ejecución: {0}",
        ["Sched_None"] = "Ninguna programación activa.",
        ["Sched_Create"] = "Crear / actualizar tarea",
        ["Sched_Remove"] = "Quitar tarea",
        ["Sched_BadTime"] = "Hora no válida. Usa el formato HH:mm.",
        ["Sched_Created"] = "Tarea programada creada/actualizada para las {0}.",
        ["Sched_Removed"] = "Tarea programada eliminada.",
        ["Sched_Error"] = "Error: {0}",

        ["Health_BannerTitle"] = "Atención a las copias",
        ["Health_BannerFormat"] = "Trabajos con problemas: {0} fallidos, {1} sin ejecutarse hace demasiado.",

        ["Preflight_ConfirmTitle"] = "Comprobaciones previas",
        ["Preflight_ConfirmIntro"] = "Algunas comprobaciones detectan posibles problemas. ¿Ejecutar de todos modos?",
        ["Preflight_DestUnreachable"] = "destino no accesible",
        ["Preflight_LowSpace"] = "poco espacio libre:",
        ["Preflight_SourceBigger"] = "el origen podría no caber; necesita:",

        ["Tray_Open"] = "Abrir",
        ["Tray_RunAll"] = "Ejecutar todo",
        ["Tray_Exit"] = "Salir",
        ["Toast_Ok"] = "Copia completada",
        ["Toast_Error"] = "Copia con errores",
    };

    // ---------------- FRANÇAIS ----------------
    private static readonly Dictionary<string, string> Fr = new()
    {
        ["Common_Browse"] = "Parcourir…",
        ["Common_Save"] = "Enregistrer",
        ["Common_Cancel"] = "Annuler",
        ["Common_MissingData"] = "Données manquantes",
        ["Common_Confirm"] = "Confirmer",

        ["Main_Title"] = "RoboKeep — Sauvegarde configurable",
        ["Main_New"] = "Nouveau",
        ["Main_Edit"] = "Modifier",
        ["Main_Delete"] = "Supprimer",
        ["Main_MoveUpTip"] = "Monter (priorité plus élevée)",
        ["Main_MoveDownTip"] = "Descendre (priorité plus basse)",
        ["Main_Preview"] = "Aperçu",
        ["Main_RunSelected"] = "Lancer la sélection",
        ["Main_RunAll"] = "Tout lancer",
        ["Main_Settings"] = "Paramètres",
        ["Main_LogTitle"] = "Journal d'exécution",
        ["Main_Clear"] = "Effacer",
        ["Main_Refresh"] = "Actualiser",
        ["DragHint"] = "Glisser pour réordonner",

        ["Col_Active"] = "Actif",
        ["Col_Name"] = "Nom",
        ["Col_Mode"] = "Mode",
        ["Col_Source"] = "Source",
        ["Col_Dest"] = "Destination",
        ["Col_LastResult"] = "Dernier résultat",

        ["Empty_Title"] = "Aucune tâche configurée",
        ["Empty_Desc"] = "Créez votre première sauvegarde : choisissez un dossier source et une destination.",
        ["Empty_Button"] = "Créer la première tâche",

        ["Status_Running"] = "Exécution en cours…",
        ["Status_JobsConfigured"] = "{0} tâches configurées",

        ["Mode_Mirror"] = "Miroir",
        ["Mode_CopyOnly"] = "Copie seule",

        ["Run_Preview"] = "APERÇU",
        ["Run_Execution"] = "EXÉCUTION",
        ["Run_PreviewStatus"] = "aperçu…",
        ["Run_InProgress"] = "en cours…",
        ["Run_OK"] = "OK",
        ["Run_Error"] = "ERREUR",
        ["Run_Cancelled"] = "annulé",
        ["Run_CancelledUser"] = "annulé par l'utilisateur",
        ["Stat_Copied"] = "copiés",
        ["Stat_Unchanged"] = "inchangés",
        ["Stat_Extra"] = "en trop",
        ["Stat_Errors"] = "erreurs",

        ["Delete_Confirm"] = "Supprimer la tâche '{0}' ?",

        ["Editor_TitleEdit"] = "Modifier la tâche",
        ["Editor_NewJobName"] = "Nouvelle tâche",
        ["Editor_Name"] = "Nom",
        ["Editor_NamePlaceholder"] = "ex. Documents",
        ["Editor_Source"] = "Source",
        ["Editor_Dest"] = "Destination",
        ["Editor_Mirror"] = "Miroir — rend la destination identique à la source (SUPPRIME les fichiers retirés)",
        ["Editor_MirrorHint"] = "Désactivé = copie et met à jour seulement, ne supprime jamais à la destination.",
        ["Editor_ExcludeOlder"] = "Ne pas écraser les fichiers plus récents à la destination (/XO)",
        ["Editor_CopyAll"] = "Copier aussi ACL/propriétaire (/COPYALL — utile sur les partages réseau)",
        ["Editor_BigJ"] = "Optimiser les gros fichiers (/J — E/S sans tampon)",
        ["Editor_BigJTip"] = "Pour les très gros fichiers (plusieurs Go) : contourne le cache du système de fichiers, souvent plus rapide sur SSD/NVMe et réseaux rapides. N'aide pas les petits fichiers. Mutuellement exclusif avec la copie reprenable.",
        ["Editor_RestartZ"] = "Copie reprenable (/Z — reprend si interrompue)",
        ["Editor_RestartZTip"] = "Reprend la copie d'un gros fichier s'il est interrompu (utile sur VPN, Wi-Fi ou réseaux peu fiables). Elle a un certain surcoût : sur les réseaux stables, mieux vaut la laisser désactivée. Mutuellement exclusive avec l'optimisation des gros fichiers.",
        ["Editor_LogAll"] = "Journaliser tous les fichiers (y compris ignorés)",
        ["Editor_LogAllTip"] = "Ajoute /V : le journal liste aussi les fichiers identiques/ignorés, pas seulement les copiés. Journal bien plus volumineux et ralentit l'exécution (une ligne par fichier). Laissez désactivé si vous n'avez pas besoin du détail.",
        ["Editor_Threads"] = "Threads (/MT)",
        ["Editor_ThreadsTip"] = "Nombre de fichiers copiés en parallèle (multi-thread). Plus élevé = plus rapide, surtout avec beaucoup de petits fichiers. 8 convient presque toujours ; 16+ sur SSD ou partages réseau rapides ; sur disques durs mécaniques, n'exagérez pas (cela peut faire travailler la tête). 0 désactive le multi-thread.",
        ["Editor_Retries"] = "Tentatives (/R)",
        ["Editor_RetriesTip"] = "Combien de fois réessayer de copier un fichier si la copie échoue (ex. fichier temporairement utilisé ou réseau instable). Avec des fichiers souvent ouverts, gardez une valeur basse (1) pour ne pas attendre longtemps.",
        ["Editor_Wait"] = "Attente sec (/W)",
        ["Editor_WaitTip"] = "Secondes d'attente entre les tentatives. Se combine avec les Tentatives (ex. 1 tentative × 5 s). Des valeurs élevées allongent beaucoup les durées en cas de fichiers problématiques.",
        ["Editor_Credential"] = "Identifiant réseau (pour les partages UNC)",
        ["Editor_CredentialTip"] = "Nécessaire seulement si la source ou la destination est un dossier réseau partagé (\\\\serveur\\partage) demandant un identifiant et un mot de passe. Les identifiants se créent dans Paramètres → Identifiants. Pour les disques locaux ou USB, laissez « aucun ».",
        ["Editor_ExcludeFiles"] = "Exclure des fichiers (un par ligne)",
        ["Editor_ExcludeFilesTip"] = "Motifs de fichiers à NE PAS copier, un par ligne. Exemples : *.tmp (tous les .tmp), ~$* (fichiers temporaires Office), *.log. Laissez vide pour tout copier.",
        ["Editor_ExcludeDirs"] = "Exclure des dossiers (un par ligne)",
        ["Editor_ExcludeDirsTip"] = "Noms de dossiers à ignorer, un par ligne. Exemples : cache, node_modules, Temp. Ils sont exclus partout où ils apparaissent dans l'arborescence.",
        ["Editor_ForceCopy"] = "Forcer la copie (ignorer date/taille)",
        ["Editor_ForceCopyTip"] = "Fichiers recopiés même si la date et la taille ne changent pas (ex. conteneurs, BdD, archives .pst). Un par ligne, par nom ou extension. Ils sont copiés en entier à chaque sauvegarde, sauf si vous activez l'option ci-dessous.",
        ["Editor_ForceCopySmart"] = "Copier seulement si le contenu a changé (calcule un hachage ; lecture plus lente)",
        ["Editor_ForceCopySmartTip"] = "Avec cette option, l'app calcule un hachage SHA256 de chaque fichier de la liste et ne le recopie que s'il a réellement changé depuis la dernière sauvegarde. Utile pour les gros fichiers qui changent rarement ; chaque sauvegarde doit toutefois les lire en entier.",
        ["Editor_ForceCopyPreviewSmart"] = "<fichiers modifiés>",
        ["Wiz_Title"] = "Nouvelle tâche — assistant de configuration",
        ["Wiz_Step"] = "Étape {0} sur {1}",
        ["Wiz_Back"] = "Précédent",
        ["Wiz_Next"] = "Suivant",
        ["Wiz_Open"] = "Ouvrir dans l'éditeur",
        ["Wiz_Skip"] = "Ignorer et configurer manuellement",
        ["Wiz_Step1Title"] = "Informations de base",
        ["Wiz_Step2Title"] = "Type de disques",
        ["Wiz_Step3Title"] = "Comportement",
        ["Wiz_Step4Title"] = "Cas particuliers",
        ["Wiz_Step5Title"] = "Récapitulatif",
        ["Wiz_SourceKind"] = "Type de source",
        ["Wiz_DestKind"] = "Type de destination",
        ["Wiz_KindHint"] = "Avec un disque dur (HDD) moins de threads sont plus rapides ; SSD et réseau supportent plus de parallélisme.",
        ["Wiz_Ssd"] = "SSD / NVMe",
        ["Wiz_Hdd"] = "Disque dur (HDD)",
        ["Wiz_Usb"] = "USB externe",
        ["Wiz_Network"] = "Partage réseau",
        ["Wiz_SyncQuestion"] = "La destination doit…",
        ["Wiz_SyncMirror"] = "Refléter la source (supprime aussi les fichiers retirés)",
        ["Wiz_SyncAccumulate"] = "Accumuler (ne supprime jamais rien)",
        ["Wiz_Large"] = "Il y a de très grands fichiers (VM, conteneurs, archives multi-Go)",
        ["Wiz_Frozen"] = "J'ai des fichiers dont le contenu change mais dont la date et la taille restent identiques",
        ["Wiz_FrozenHint"] = "Ex. conteneurs VeraCrypt ou bases de données. Pour VeraCrypt, il est préférable de désactiver l'option qui conserve la date du conteneur plutôt que de le recopier à chaque fois.",
        ["Wiz_FrozenPatterns"] = "Modèles (un par ligne, ex. *.vc)",
        ["Wiz_Perms"] = "Conserver les permissions/ACL et les propriétaires des fichiers",
        ["Wiz_PermsHint"] = "Nécessaire pour restaurer sur un autre PC/serveur ; peut provoquer un accès refusé lors des recopies.",
        ["Wiz_Excl"] = "Exclure les dossiers de cache et les fichiers temporaires courants",
        ["Wiz_Summary"] = "Ce qui sera configuré",
        ["Wiz_NetCredNote"] = "Source ou destination sur le réseau : pensez à définir les identifiants dans l'éditeur.",
        ["Editor_CommandPreview"] = "Aperçu de la commande robocopy",
        ["Editor_Val_Name"] = "Le nom de la tâche est obligatoire.",
        ["Editor_Val_Source"] = "Le dossier source est obligatoire.",
        ["Editor_Val_Dest"] = "Le dossier de destination est obligatoire.",
        ["Editor_BrowseTitle"] = "Sélectionner un dossier",
        ["Cred_NoneLocal"] = "(aucun — chemin local)",

        ["Settings_Title"] = "Paramètres",
        ["Tab_General"] = "Général",
        ["Tab_Email"] = "E-mail",
        ["Tab_Credentials"] = "Identifiants réseau",
        ["Tab_Schedule"] = "Planification",
        ["Tab_About"] = "À propos",
        ["About_Version"] = "Version",
        ["About_Desc"] = "GUI de sauvegarde et de mise en miroir basée sur robocopy de Windows.",
        ["About_License"] = "Licence MIT",
        ["About_BuiltOn"] = "Basé sur le robocopy du système et .NET 10 (WPF) · 5 langues",

        ["Set_Language"] = "Langue",
        ["Lang_Auto"] = "Automatique (Windows)",
        ["Set_LogFolder"] = "Dossier des journaux (archivés par date)",
        ["Set_TempFolder"] = "Dossier temporaire",
        ["Set_PathsHint"] = "Les journaux sont TOUJOURS actifs. Si vous laissez ces champs vides, les journaux et les fichiers temporaires vont dans les sous-dossiers par défaut affichés en gris (à côté de l'app). Renseignez un chemin uniquement pour les déplacer ailleurs.",
        ["Set_Compress"] = "Compresser les journaux en .zip",
        ["Set_Retention"] = "Jours de conservation des journaux (0 = ne pas supprimer)",
        ["Set_CredSecurity"] = "Sécurité des identifiants",
        ["Set_CredScopeUser"] = "Chiffrer les mots de passe uniquement pour mon utilisateur Windows (plus sûr)",
        ["Set_CredScopeHint"] = "Activé : mots de passe (identifiants et e-mail) déchiffrables uniquement par votre utilisateur ; en contrepartie la tâche planifiée doit s'exécuter avec votre même utilisateur. Désactivé : liés au PC, fonctionnent avec n'importe quel utilisateur (pratique pour la planification). En changeant l'option, les mots de passe déjà enregistrés sont re-chiffrés automatiquement.",

        ["Email_Enable"] = "Activer les notifications par e-mail",
        ["Email_OnlyError"] = "Envoyer uniquement en cas d'erreur",
        ["Email_Smtp"] = "Serveur SMTP",
        ["Email_Port"] = "Port",
        ["Email_Ssl"] = "Utiliser SSL/TLS",
        ["Email_From"] = "De (expéditeur)",
        ["Email_To"] = "À (destinataire)",
        ["Email_User"] = "Utilisateur SMTP (facultatif)",
        ["Email_Pwd"] = "Mot de passe SMTP (laisser vide pour ne pas changer)",
        ["Email_TestButton"] = "Envoyer un e-mail de test",
        ["Email_TestSending"] = "Envoi en cours…",
        ["Email_TestSent"] = "E-mail de test envoyé. Vérifiez votre boîte (ou l'inbox Mailtrap).",
        ["Common_Error"] = "Erreur : {0}",

        ["Cred_AddUpdate"] = "Ajouter / mettre à jour un identifiant",
        ["Cred_Name"] = "Nom",
        ["Cred_Host"] = "Hôte/Partage (\\\\serveur\\partage)",
        ["Cred_User"] = "Utilisateur (DOMAINE\\utilisateur)",
        ["Cred_Pwd"] = "Mot de passe",
        ["Cred_Save"] = "Enregistrer les identifiants",
        ["Cred_Remove"] = "Retirer la sélection",
        ["Cred_ColUser"] = "Utilisateur",
        ["Cred_NameRequired"] = "Le nom de l'identifiant est obligatoire.",
        ["Conn_Test"] = "Tester la connexion",
        ["Conn_Testing"] = "Test en cours…",
        ["Conn_Ok"] = "Connexion réussie.",
        ["Conn_LogonFail"] = "Nom d'utilisateur ou mot de passe incorrect.",
        ["Conn_PathNotFound"] = "Chemin réseau introuvable (hôte injoignable).",
        ["Conn_NameNotFound"] = "Partage introuvable.",
        ["Conn_AccessDenied"] = "Accès refusé.",
        ["Conn_Generic"] = "Erreur de connexion (code {0}).",

        ["Sched_InfoTitle"] = "Exécution automatique",
        ["Sched_InfoMsg"] = "Enregistre une tâche dans le Planificateur de tâches Windows qui exécute « Tout lancer » en silence à l'heure choisie.",
        ["Sched_Time"] = "Heure (HH:mm)",
        ["Sched_Freq"] = "Fréquence",
        ["Sched_Daily"] = "Quotidienne",
        ["Sched_Weekly"] = "Hebdomadaire",
        ["Sched_Once"] = "Une seule fois",
        ["Sched_Next"] = "Prochaine exécution : {0}",
        ["Sched_None"] = "Aucune planification active.",
        ["Sched_Create"] = "Créer / mettre à jour la tâche",
        ["Sched_Remove"] = "Supprimer la tâche",
        ["Sched_BadTime"] = "Heure non valide. Utilisez le format HH:mm.",
        ["Sched_Created"] = "Tâche planifiée créée/mise à jour pour {0}.",
        ["Sched_Removed"] = "Tâche planifiée supprimée.",
        ["Sched_Error"] = "Erreur : {0}",

        ["Health_BannerTitle"] = "Attention aux sauvegardes",
        ["Health_BannerFormat"] = "Tâches en problème : {0} en échec, {1} inactives depuis trop longtemps.",

        ["Preflight_ConfirmTitle"] = "Vérifications avant lancement",
        ["Preflight_ConfirmIntro"] = "Certaines vérifications signalent des problèmes possibles. Lancer quand même ?",
        ["Preflight_DestUnreachable"] = "destination injoignable",
        ["Preflight_LowSpace"] = "espace libre faible :",
        ["Preflight_SourceBigger"] = "la source pourrait ne pas tenir ; nécessite :",

        ["Tray_Open"] = "Ouvrir",
        ["Tray_RunAll"] = "Tout lancer",
        ["Tray_Exit"] = "Quitter",
        ["Toast_Ok"] = "Sauvegarde terminée",
        ["Toast_Error"] = "Sauvegarde avec des erreurs",
    };

    // ---------------- DEUTSCH ----------------
    private static readonly Dictionary<string, string> De = new()
    {
        ["Common_Browse"] = "Durchsuchen…",
        ["Common_Save"] = "Speichern",
        ["Common_Cancel"] = "Abbrechen",
        ["Common_MissingData"] = "Fehlende Daten",
        ["Common_Confirm"] = "Bestätigen",

        ["Main_Title"] = "RoboKeep — Konfigurierbares Backup",
        ["Main_New"] = "Neu",
        ["Main_Edit"] = "Bearbeiten",
        ["Main_Delete"] = "Löschen",
        ["Main_MoveUpTip"] = "Nach oben (höhere Priorität)",
        ["Main_MoveDownTip"] = "Nach unten (niedrigere Priorität)",
        ["Main_Preview"] = "Vorschau",
        ["Main_RunSelected"] = "Ausgewählten starten",
        ["Main_RunAll"] = "Alle starten",
        ["Main_Settings"] = "Einstellungen",
        ["Main_LogTitle"] = "Ausführungsprotokoll",
        ["Main_Clear"] = "Leeren",
        ["Main_Refresh"] = "Aktualisieren",
        ["DragHint"] = "Zum Umsortieren ziehen",

        ["Col_Active"] = "Aktiv",
        ["Col_Name"] = "Name",
        ["Col_Mode"] = "Modus",
        ["Col_Source"] = "Quelle",
        ["Col_Dest"] = "Ziel",
        ["Col_LastResult"] = "Letztes Ergebnis",

        ["Empty_Title"] = "Keine Aufträge konfiguriert",
        ["Empty_Desc"] = "Erstelle dein erstes Backup: Wähle einen Quellordner und ein Ziel.",
        ["Empty_Button"] = "Ersten Auftrag erstellen",

        ["Status_Running"] = "Wird ausgeführt…",
        ["Status_JobsConfigured"] = "{0} konfigurierte Aufträge",

        ["Mode_Mirror"] = "Spiegel",
        ["Mode_CopyOnly"] = "Nur kopieren",

        ["Run_Preview"] = "VORSCHAU",
        ["Run_Execution"] = "AUSFÜHRUNG",
        ["Run_PreviewStatus"] = "Vorschau…",
        ["Run_InProgress"] = "läuft…",
        ["Run_OK"] = "OK",
        ["Run_Error"] = "FEHLER",
        ["Run_Cancelled"] = "abgebrochen",
        ["Run_CancelledUser"] = "vom Benutzer abgebrochen",
        ["Stat_Copied"] = "kopiert",
        ["Stat_Unchanged"] = "unverändert",
        ["Stat_Extra"] = "zusätzlich",
        ["Stat_Errors"] = "Fehler",

        ["Delete_Confirm"] = "Auftrag '{0}' löschen?",

        ["Editor_TitleEdit"] = "Auftrag bearbeiten",
        ["Editor_NewJobName"] = "Neuer Auftrag",
        ["Editor_Name"] = "Name",
        ["Editor_NamePlaceholder"] = "z. B. Dokumente",
        ["Editor_Source"] = "Quelle",
        ["Editor_Dest"] = "Ziel",
        ["Editor_Mirror"] = "Spiegel — macht das Ziel identisch zur Quelle (LÖSCHT entfernte Dateien)",
        ["Editor_MirrorHint"] = "Deaktiviert = kopiert und aktualisiert nur, löscht nie am Ziel.",
        ["Editor_ExcludeOlder"] = "Neuere Dateien am Ziel nicht überschreiben (/XO)",
        ["Editor_CopyAll"] = "Auch ACLs/Besitzer kopieren (/COPYALL — nützlich bei Netzwerkfreigaben)",
        ["Editor_BigJ"] = "Große Dateien optimieren (/J — ungepufferte E/A)",
        ["Editor_BigJTip"] = "Für sehr große Dateien (mehrere GB): umgeht den Dateisystem-Cache, oft schneller auf SSD/NVMe und schnellen Netzwerken. Hilft nicht bei kleinen Dateien. Schließt sich mit der fortsetzbaren Kopie gegenseitig aus.",
        ["Editor_RestartZ"] = "Fortsetzbare Kopie (/Z — setzt nach Abbruch fort)",
        ["Editor_RestartZTip"] = "Setzt das Kopieren einer großen Datei fort, wenn es unterbrochen wird (nützlich bei VPN, WLAN oder unzuverlässigen Netzwerken). Hat etwas Mehraufwand: in stabilen Netzwerken besser deaktiviert lassen. Schließt sich mit der Optimierung großer Dateien gegenseitig aus.",
        ["Editor_LogAll"] = "Alle Dateien protokollieren (auch übersprungene)",
        ["Editor_LogAllTip"] = "Fügt /V hinzu: das Protokoll listet auch identische/übersprungene Dateien, nicht nur kopierte. Viel umfangreicheres Protokoll und verlangsamt die Ausführung (eine Zeile pro Datei). Lassen Sie es aus, wenn Sie das Detail nicht brauchen.",
        ["Editor_Threads"] = "Threads (/MT)",
        ["Editor_ThreadsTip"] = "Anzahl der parallel kopierten Dateien (Multithread). Höher = schneller, besonders bei vielen kleinen Dateien. 8 passt fast immer; 16+ auf SSDs oder schnellen Netzwerkfreigaben; bei mechanischen Festplatten nicht übertreiben (kann den Kopf stark bewegen). 0 deaktiviert Multithread.",
        ["Editor_Retries"] = "Wiederholungen (/R)",
        ["Editor_RetriesTip"] = "Wie oft das Kopieren einer Datei wiederholt wird, wenn es fehlschlägt (z. B. Datei vorübergehend in Benutzung oder instabiles Netzwerk). Bei oft geöffneten Dateien einen niedrigen Wert (1) wählen, um nicht lange zu warten.",
        ["Editor_Wait"] = "Wartezeit Sek (/W)",
        ["Editor_WaitTip"] = "Sekunden Wartezeit zwischen den Versuchen. Kombiniert sich mit den Wiederholungen (z. B. 1 Versuch × 5 Sek). Hohe Werte verlängern die Zeiten stark, wenn es problematische Dateien gibt.",
        ["Editor_Credential"] = "Netzwerk-Anmeldedaten (für UNC-Freigaben)",
        ["Editor_CredentialTip"] = "Nur nötig, wenn Quelle oder Ziel ein freigegebener Netzwerkordner (\\\\Server\\Freigabe) ist, der Benutzer und Passwort erfordert. Anmeldedaten werden in Einstellungen → Anmeldedaten erstellt. Für lokale oder USB-Laufwerke « keine » lassen.",
        ["Editor_ExcludeFiles"] = "Dateien ausschließen (eine pro Zeile)",
        ["Editor_ExcludeFilesTip"] = "Dateimuster, die NICHT kopiert werden, eines pro Zeile. Beispiele: *.tmp (alle .tmp), ~$* (Office-Temporärdateien), *.log. Leer lassen, um alles zu kopieren.",
        ["Editor_ExcludeDirs"] = "Ordner ausschließen (einer pro Zeile)",
        ["Editor_ExcludeDirsTip"] = "Ordnernamen, die übersprungen werden, einer pro Zeile. Beispiele: cache, node_modules, Temp. Sie werden überall im Baum ausgeschlossen, wo sie vorkommen.",
        ["Editor_ForceCopy"] = "Kopie erzwingen (Datum/Größe ignorieren)",
        ["Editor_ForceCopyTip"] = "Dateien, die auch dann neu kopiert werden, wenn Datum und Größe gleich bleiben (z. B. Container, DBs, .pst-Archive). Eine pro Zeile, nach Name oder Endung. Sie werden bei jeder Sicherung vollständig kopiert, sofern Sie die Option unten nicht aktivieren.",
        ["Editor_ForceCopySmart"] = "Nur kopieren, wenn sich der Inhalt geändert hat (berechnet Hash; langsameres Lesen)",
        ["Editor_ForceCopySmartTip"] = "Mit dieser Option berechnet die App einen SHA256-Hash jeder aufgelisteten Datei und kopiert sie nur neu, wenn sie sich seit der letzten Sicherung tatsächlich geändert hat. Nützlich für große Dateien, die sich selten ändern; jede Sicherung muss sie jedoch vollständig lesen.",
        ["Editor_ForceCopyPreviewSmart"] = "<geänderte Dateien>",
        ["Wiz_Title"] = "Neuer Auftrag — Einrichtungsassistent",
        ["Wiz_Step"] = "Schritt {0} von {1}",
        ["Wiz_Back"] = "Zurück",
        ["Wiz_Next"] = "Weiter",
        ["Wiz_Open"] = "Im Editor öffnen",
        ["Wiz_Skip"] = "Überspringen und manuell konfigurieren",
        ["Wiz_Step1Title"] = "Grunddaten",
        ["Wiz_Step2Title"] = "Laufwerkstypen",
        ["Wiz_Step3Title"] = "Verhalten",
        ["Wiz_Step4Title"] = "Sonderfälle",
        ["Wiz_Step5Title"] = "Zusammenfassung",
        ["Wiz_SourceKind"] = "Quelltyp",
        ["Wiz_DestKind"] = "Zieltyp",
        ["Wiz_KindHint"] = "Bei einer Festplatte (HDD) sind weniger Threads schneller; SSD und Netzwerk vertragen mehr Parallelismus.",
        ["Wiz_Ssd"] = "SSD / NVMe",
        ["Wiz_Hdd"] = "Festplatte (HDD)",
        ["Wiz_Usb"] = "Externer USB",
        ["Wiz_Network"] = "Netzwerkfreigabe",
        ["Wiz_SyncQuestion"] = "Das Ziel soll…",
        ["Wiz_SyncMirror"] = "Die Quelle spiegeln (löscht auch entfernte Dateien)",
        ["Wiz_SyncAccumulate"] = "Ansammeln (löscht nie etwas)",
        ["Wiz_Large"] = "Es gibt sehr große Dateien (VMs, Container, mehrgigabyte Archive)",
        ["Wiz_Frozen"] = "Ich habe Dateien, deren Inhalt sich ändert, aber Datum und Größe gleich bleiben",
        ["Wiz_FrozenHint"] = "Z. B. VeraCrypt-Container oder Datenbanken. Bei VeraCrypt empfiehlt es sich, die Option zum Beibehalten des Container-Zeitstempels zu deaktivieren, statt ihn jedes Mal neu zu kopieren.",
        ["Wiz_FrozenPatterns"] = "Muster (eines pro Zeile, z. B. *.vc)",
        ["Wiz_Perms"] = "Dateiberechtigungen/ACLs und Eigentümer beibehalten",
        ["Wiz_PermsHint"] = "Wird zum Wiederherstellen auf einem anderen PC/Server benötigt; kann bei Neukopiervorgängen zu Zugriff verweigert führen.",
        ["Wiz_Excl"] = "Gemeinsame Cache-Ordner und temporäre Dateien ausschließen",
        ["Wiz_Summary"] = "Was eingestellt wird",
        ["Wiz_NetCredNote"] = "Quelle oder Ziel im Netzwerk: Vergessen Sie nicht, die Anmeldedaten im Editor einzustellen.",
        ["Editor_CommandPreview"] = "Vorschau des robocopy-Befehls",
        ["Editor_Val_Name"] = "Der Auftragsname ist erforderlich.",
        ["Editor_Val_Source"] = "Der Quellordner ist erforderlich.",
        ["Editor_Val_Dest"] = "Der Zielordner ist erforderlich.",
        ["Editor_BrowseTitle"] = "Ordner auswählen",
        ["Cred_NoneLocal"] = "(keine — lokaler Pfad)",

        ["Settings_Title"] = "Einstellungen",
        ["Tab_General"] = "Allgemein",
        ["Tab_Email"] = "E-Mail",
        ["Tab_Credentials"] = "Netzwerk-Anmeldedaten",
        ["Tab_Schedule"] = "Planung",
        ["Tab_About"] = "Info",
        ["About_Version"] = "Version",
        ["About_Desc"] = "GUI für Backups und Spiegelung auf Basis von Windows-robocopy.",
        ["About_License"] = "MIT-Lizenz",
        ["About_BuiltOn"] = "Basiert auf dem System-robocopy und .NET 10 (WPF) · 5 Sprachen",

        ["Set_Language"] = "Sprache",
        ["Lang_Auto"] = "Automatisch (Windows)",
        ["Set_LogFolder"] = "Protokollordner (nach Datum archiviert)",
        ["Set_TempFolder"] = "Temporärer Ordner",
        ["Set_PathsHint"] = "Protokolle sind IMMER aktiv. Wenn du diese Felder leer lässt, gehen Protokolle und temporäre Dateien in die grau angezeigten Standard-Unterordner (neben der App). Gib einen Pfad nur an, um sie woanders hin zu verschieben.",
        ["Set_Compress"] = "Protokolle als .zip komprimieren",
        ["Set_Retention"] = "Aufbewahrungstage für Protokolle (0 = nicht löschen)",
        ["Set_CredSecurity"] = "Anmeldedaten-Sicherheit",
        ["Set_CredScopeUser"] = "Passwörter nur für meinen Windows-Benutzer verschlüsseln (sicherer)",
        ["Set_CredScopeHint"] = "Aktiv: Passwörter (Anmeldedaten und E-Mail) nur von deinem Benutzer entschlüsselbar; dafür muss die geplante Aufgabe mit deinem Benutzer laufen. Inaktiv: an den PC gebunden, funktionieren mit jedem Benutzer (praktisch für die Planung). Beim Ändern der Option werden bereits gespeicherte Passwörter automatisch neu verschlüsselt.",

        ["Email_Enable"] = "E-Mail-Benachrichtigungen aktivieren",
        ["Email_OnlyError"] = "Nur bei Fehler senden",
        ["Email_Smtp"] = "SMTP-Server",
        ["Email_Port"] = "Port",
        ["Email_Ssl"] = "SSL/TLS verwenden",
        ["Email_From"] = "Von (Absender)",
        ["Email_To"] = "An (Empfänger)",
        ["Email_User"] = "SMTP-Benutzer (optional)",
        ["Email_Pwd"] = "SMTP-Passwort (leer lassen zum Beibehalten)",
        ["Email_TestButton"] = "Test-E-Mail senden",
        ["Email_TestSending"] = "Wird gesendet…",
        ["Email_TestSent"] = "Test-E-Mail gesendet. Prüfe dein Postfach (oder die Mailtrap-Inbox).",
        ["Common_Error"] = "Fehler: {0}",

        ["Cred_AddUpdate"] = "Anmeldedaten hinzufügen / aktualisieren",
        ["Cred_Name"] = "Name",
        ["Cred_Host"] = "Host/Freigabe (\\\\Server\\Freigabe)",
        ["Cred_User"] = "Benutzer (DOMÄNE\\Benutzer)",
        ["Cred_Pwd"] = "Passwort",
        ["Cred_Save"] = "Anmeldedaten speichern",
        ["Cred_Remove"] = "Auswahl entfernen",
        ["Cred_ColUser"] = "Benutzer",
        ["Cred_NameRequired"] = "Der Name der Anmeldedaten ist erforderlich.",
        ["Conn_Test"] = "Verbindung testen",
        ["Conn_Testing"] = "Wird getestet…",
        ["Conn_Ok"] = "Verbindung erfolgreich.",
        ["Conn_LogonFail"] = "Benutzername oder Passwort falsch.",
        ["Conn_PathNotFound"] = "Netzwerkpfad nicht gefunden (Host nicht erreichbar).",
        ["Conn_NameNotFound"] = "Freigabe nicht gefunden.",
        ["Conn_AccessDenied"] = "Zugriff verweigert.",
        ["Conn_Generic"] = "Verbindungsfehler (Code {0}).",

        ["Sched_InfoTitle"] = "Automatische Ausführung",
        ["Sched_InfoMsg"] = "Registriert eine Aufgabe in der Windows-Aufgabenplanung, die « Alle starten » zur gewählten Zeit unbeaufsichtigt ausführt.",
        ["Sched_Time"] = "Uhrzeit (HH:mm)",
        ["Sched_Freq"] = "Häufigkeit",
        ["Sched_Daily"] = "Täglich",
        ["Sched_Weekly"] = "Wöchentlich",
        ["Sched_Once"] = "Einmalig",
        ["Sched_Next"] = "Nächste Ausführung: {0}",
        ["Sched_None"] = "Keine aktive Planung.",
        ["Sched_Create"] = "Aufgabe erstellen / aktualisieren",
        ["Sched_Remove"] = "Aufgabe entfernen",
        ["Sched_BadTime"] = "Ungültige Uhrzeit. Verwende das Format HH:mm.",
        ["Sched_Created"] = "Geplante Aufgabe erstellt/aktualisiert für {0}.",
        ["Sched_Removed"] = "Geplante Aufgabe entfernt.",
        ["Sched_Error"] = "Fehler: {0}",

        ["Health_BannerTitle"] = "Achtung bei Backups",
        ["Health_BannerFormat"] = "Jobs mit Problemen: {0} fehlgeschlagen, {1} zu lange nicht ausgeführt.",

        ["Preflight_ConfirmTitle"] = "Prüfungen vor dem Start",
        ["Preflight_ConfirmIntro"] = "Einige Prüfungen melden mögliche Probleme. Trotzdem starten?",
        ["Preflight_DestUnreachable"] = "Ziel nicht erreichbar",
        ["Preflight_LowSpace"] = "wenig freier Speicher:",
        ["Preflight_SourceBigger"] = "die Quelle passt evtl. nicht; benötigt:",

        ["Tray_Open"] = "Öffnen",
        ["Tray_RunAll"] = "Alle starten",
        ["Tray_Exit"] = "Beenden",
        ["Toast_Ok"] = "Backup abgeschlossen",
        ["Toast_Error"] = "Backup mit Fehlern",
    };

    // Mappa lingua → dizionario. Dichiarata DOPO i dizionari, così sono già inizializzati
    // quando questo inizializzatore viene eseguito (ordine testuale degli static).
    private static readonly Dictionary<string, Dictionary<string, string>> Langs = new()
    {
        ["it"] = It,
        ["en"] = En,
        ["es"] = Es,
        ["fr"] = Fr,
        ["de"] = De,
    };
}
